### ISSUE TITLE
How to change text Progress bar?

### ISSUE THREAD

**Issue by huynn109** [linsea/UniversalVideoView#10]
I want change text progress bar to english, please?

**Comment by linsea** [comment]
@huynn109 
1. download the project, and add it as a project dependency in you app `settings.gradle` and `build.gradle` file.
2. replacing the corresponding Chinese word with your native word in these layout files: `universalvideoview/src/main/res/layout/*.xml`.
I would add English language support some day if needed.

**Comment by ivxn31** [comment]
Es un textview del cual puede buscar con el id de loading_text

solo necesita hacer lo siguiente
private TextView loading_text;
loading_text = view.findViewById(R.id.loading_text);
loading_text.setText("Loading");
