### ISSUE TITLE
some video url is not play

### ISSUE THREAD

**Issue by dineshswaas** [linsea/UniversalVideoView#13]
https://media011.blob.core.windows.net/000/SampleVideo_1080x720_5mb_13d4df3c-e931-4a7f-bc0e-4ad985b97524.mp4

Above URL is not playing,what is the reason?

**Comment by linsea** [comment]
@dineshswaas Can the Android native VideoView play?

**Comment by linsea** [comment]
http://stackoverflow.com/questions/30166725/android-media-player-streaming-audio-file-from-https-url
