### ISSUE TITLE
请问全屏时在魅族和华为手机上怎么老是有一块白色区域，差不多有一个状态栏的高度？急急急

### ISSUE THREAD

**Issue by shitou9999** [linsea/UniversalVideoView#15]

**Comment by linsea** [comment]
@shitou9999 你用DDMS调试看下那个是什么View, 可能在全屏时没有手动设置为gone

**Comment by shitou9999** [comment]
![Uploading QQ截图20160809191350.png…]()
我确定我所有的无用的view都gone掉了，ScrollView里面嵌套了一个LinearLayout，DDMS时可以看到它俩之间有些间隔，margin和padding我确定都去掉了，这该怎么办？

**Comment by shitou9999** [comment]
[Uploading QQ截图20160809191350.png…]()
我确定我所有的无用的view都gone掉了，ScrollView里面嵌套了一个LinearLayout，DDMS时可以看到它俩之间有些间隔，margin和padding我确定都去掉了，这该怎么办？-------不小心关掉了，再发一遍吧省的你看不见

**Comment by linsea** [comment]
@shitou9999 这个是正常的现象, 像系统的VideoView一样, UniversalVideoView播放视频默认是按比例缩放的, 比如这个视频如果按手机的宽度来播放的话, 高度不够,则必须上下会各留一条黑带, 你说出现白色的, 应该是父布局的背景是白色的. 如果你不想按比例来缩放的话, 可以设置:
```xml
        <com.universalvideoview.UniversalVideoView
            app:uvv_fitXY="true" />
```
这样就会使视频XY轴拉升至铺满父布局.
华为和魅族都有虚拟按键, 导致可用的播放区域不是通常的16:9的比例, 因此上下会留空白.
修改以上属性你再试试.

**Comment by shitou9999** [comment]
我试了试，确实是ScrollView的颜色， app:uvv_fitXY="true"但是我设了这个属性，白色区域比原来的大了三倍，还有别的办法处理吗?

**Comment by linsea** [comment]
@shitou9999 把视频区单独放在一个父布局里, 把这个布局的背景设置为黑色的, 然后再把这个布局放在ScrollView的子布局(比如是LinearLayout)的布局里面. 特别注意的一点是你需要根据视频适配视频区父布局的高度,以保证视频播放时以你期望的方式展示.

**Comment by shitou9999** [comment]
@linsea 我按你说的用项目中的视频空白区域比原来的还大，估计就是视频适配视频区域父布局高度的问题，这个问题怎么处理？麻烦你了

**Comment by linsea** [comment]
@shitou9999 你需要知道播放视频的长宽比, 然后据此来计算播放区的高度, 把播放区高度设置为计算的高度值, 这样适配视频就可以不用设置为fixXY,播放时也是按比例缩放的.

**Comment by shitou9999** [comment]
@linsea 非常非常感谢！！！！
