### ISSUE TITLE
Failed to resolve: com.linsea:universalvideoview:1.1.0

### ISSUE THREAD

**Issue by fukemy** [linsea/UniversalVideoView#21]
Failed to resolve: com.linsea:universalvideoview:1.1.0
Hello. How can i use it ? Thanks.

**Comment by linsea** [comment]
I just tested, the library can be downloaded by AS.
Do you set "offline" mode in your AS?
alternatively you can download manually from [here](https://bintray.com/linsea/maven/download_file?file_path=com%2Flinsea%2Funiversalvideoview%2F1.1.0%2Funiversalvideoview-1.1.0.aar), and put it on your project.
