### ISSUE TITLE
播放器隐藏时可能出现mMediaController为null

### ISSUE THREAD

**Issue by liongoodvery** [linsea/UniversalVideoView#22]
UniversalVideoView line 844 `mMediaController.toggleButtons(fullscreen);`
这里mMediaController有可能为null
具体场景：有些页面需要播放视频，有些页面不需要．通过是否有是否有视频url决定是否隐藏播放器．当隐藏播放器时，mMediaController值并没有被设置，当屏幕选择时，mMediaController为null,导致程序崩溃．

**Comment by linsea** [comment]
@liongoodvery 你可以在应用层作一些防御性检查
