### ISSUE TITLE
切换横竖屏时的问题，希望解答一下

### ISSUE THREAD

**Issue by scyACE** [linsea/UniversalVideoView#28]
![qq 20170517163932](https://cloud.githubusercontent.com/assets/24730234/26145651/c900f020-3b1f-11e7-8a36-fcdcc72ccab1.jpg)
切换横屏就会这样，点击一下就全屏，之后会又变成这样

**Comment by linsea** [comment]
模拟器有点问题, 你用真机试吧. #16
