### ISSUE TITLE
播放视频出现一卡一顿，放2秒就黑屏显示加载中，然后又好了，再放2秒继续黑屏加载，完全不能用

### ISSUE THREAD

**Issue by icaruslucifer** [linsea/UniversalVideoView#30]
播放视频出现一卡一顿，放2秒就黑屏显示加载中，然后又好了，再放2秒继续黑屏加载，完全不能用

**Comment by linsea** [comment]
卡顿那是因为在缓冲中，黑屏是因为LoadingView的背景设置为黑色的了，以防SurfaceView穿透，如果你不想这样，可以自定义透明背景的loadingView, 通过UniversalMediaController.setOnLoadingView(...)设置进去就行了。
