### ISSUE TITLE
How To Change loading language to english

### ISSUE THREAD

**Issue by AsfanUlla** [linsea/UniversalVideoView#33]

**Comment by YangShaoXiong** [comment]
@AsfanUlla please modify id is "loading_text" TextView, hyperlink is [https://github.com/linsea/UniversalVideoView/blob/a77a55f91bdc193a0548bf1472280558c28ddd97/universalvideoview/src/main/res/layout/uvv_on_loading_layout.xml]()

**Comment by linsea** [comment]
@AsfanUlla ref: #10

**Comment by ivxn31** [comment]
Es una vista de texto del cual puede buscarse con el id de cargando texto

solo necesita hacer lo siguiente 
privado TextView loading_text; 
loading_text = view.findViewById (R.id.loading_text); 
loading_text.setText ("Loading...");
