### ISSUE TITLE
Loading progress title

### ISSUE THREAD

**Issue by prossik** [linsea/UniversalVideoView#38]
Hi @linsea , thanks for your awesome lib. Can you please provide me instruction how to change progress loading title. To see image please check attachments. Thanks!
![title_player](https://user-images.githubusercontent.com/12844739/31227424-7c550f90-a9e2-11e7-9cd5-8ce2ff6bd985.png)

**Comment by linsea** [comment]
see #10

**Comment by ivxn31** [comment]
Es un textview del cual puede buscar con el id de loading_text

solo necesita hacer lo siguiente

private TextView loading_text;
loading_text = view.findViewById(R.id.loading_text);
loading_text.setText("Loading...");
