### ISSUE TITLE
How to check end time of video when video is pause and activity pause,destroyed,stop

### ISSUE THREAD

**Issue by rssumit** [linsea/UniversalVideoView#42]
How to check end time of video when the video is pause and activity pause, destroyed, stop.
When the user starts the video, if he pauses the video and go back(pause, stop, destroyed activity,pause video).after this video should start from last timestamp.

**Comment by linsea** [comment]
see the sample:
save your video position on `protected void onSaveInstanceState(Bundle outState)`;
and when user back,  on `public void onStart(MediaPlayer mediaPlayer) ` seek to the saved position :
```
    @Override
    public void onStart(MediaPlayer mediaPlayer) {
        Log.d(TAG, "onStart UniversalVideoView callback");
        mVideoView.seekTo(mSeekPosition);  // seek to the saved position
    }
```
