### ISSUE TITLE
Fullscreen button has to be pressed twice to enter full screen

### ISSUE THREAD

**Issue by nicholaswhittle** [linsea/UniversalVideoView#43]
Im trying to use your video view but when i press the full screen button, the orientation changes but it is a not truly full screen. The bottom and top layouts are off screen, and then when i press the fullscreen button again the video goes full screen as expected.

Iv tried to debug the code but can't see where this is happening, the setfullscreen method is called as usual but it seems that it needs to be called twice.

Help would be appreciated

**Comment by linsea** [comment]
Can you provide your phone infomation ? The App you ran is the sample APP?

**Comment by nicholaswhittle** [comment]
Hey, so i didn't end up fixing this and can't figure it out. Would appreciate some help

I basically have only changed the video layout size, think of youtube app where the video is at the top and then information below it. So the video is embedded within the view.

When i click the fullscreen button, it changes orientation and goes full screen. But the supportBar is still on screen. And the bottom of the video layout is off screen (the control buttons are not on screen)
It seems that its not accounting for the supportbar. 

I have tried to hide the supportbar on orientationChange, but it comes back straight away (only noticable when i breakpoint)

So if i remove the supportbar completely within the activity. It behaves as expected. But i require the supportbar on my activity.

**Comment by nicholaswhittle** [comment]
Ok turned out i needed to reread your docs.
I added `android:configChanges="orientation|keyboardHidden|screenSize"` into manifest and this stopped it.
As yo said it was recreating the activity.
