### ISSUE TITLE
请问怎样设置播放前的背景图片

### ISSUE THREAD

**Issue by mniysh** [linsea/UniversalVideoView#5]
请问怎样设置播放前的背景图片

**Comment by linsea** [comment]
@mniysh 
UniversalMediaController#setOnLoadingView

**Comment by mniysh** [comment]
我用这个方法加载了一个本地drawable中的图片，报错Resources$NotFoundException: File res/drawable/banner.png from xml type layout resource ID #0x7f02003e

**Comment by linsea** [comment]
@mniysh 参数要求是layout id,而不是drawable id. 你需要自己写个布局把drawable包装下。

**Comment by mniysh** [comment]
这个的确是不报错了，但是不是我说的那种，我的意思是视频播放之前展示播放区域的背景图片。不是加载的图片，类似截取视频第一帧作为背景图片，点击播放，显示加载中，开始播放后背景消失显示播放内容。

**Comment by linsea** [comment]
@mniysh 这种需求， 一般是服务器已经预先存有一张图的，开始播放时先从网络加载这张图片，不是播放时从视频文件中截取的，视频还没有加载出来，哪有第一帧呢，也没有那么快，而从服务器加载一张图一般比较快，在视频开始播放前就已经出来了。

**Comment by mniysh** [comment]
你说的有道理，我们这也是服务器有图片的，现在需求是 ：播放前就把服务器的图放到播放区域，不是播放时从服务器加载。现在您的项目是默认黑色背景（在没播放之前），请问您项目中有没有封装这个方法呢。

在 2016-04-14 09:35:27，"Linsea" <notifications@github.com> 写道：


@mniysh 这种需求， 一般是服务器已经预先存有一张图的，开始播放时先从网络加载这张图片，不是播放时从视频文件中截取的，视频还没有加载出来，哪有第一帧呢，也没有那么快，而从服务器加载一张图一般比较快，在视频开始播放前就已经出来了。

**Comment by linsea** [comment]
@mniysh 我觉得你可以定义一个ImageView放在播放器上面，把播放器遮住，然后你按你的需求在适当的时候自己处理相应的显示与隐藏就行了。

**Comment by mniysh** [comment]
嗯嗯，就是这样做的
