### ISSUE TITLE
请问这个项目是否支持RTMP流播放

### ISSUE THREAD

**Issue by KingKatsuma** [linsea/UniversalVideoView#6]
RT

**Comment by linsea** [comment]
底层使用的是系统的MediaPlayer播放器，是支持RTMP的。

**Comment by KingKatsuma** [comment]
我使用如下rtmp流播放地址
private static final String VIDEO_URL = "rtmp://live.hkstv.hk.lxdns.com/live/hks";
通过如下方式设置
mVideoView.setVideoPath(VIDEO_URL);
报错
Failed to open file 'rtmp://live.hkstv.hk.lxdns.com/live/hks'. (No such file or directory)
被认为是文件地址了

**Comment by linsea** [comment]
不好意思，我看错了，MediaPlayer目前不支持RTMP流媒体格式：
http://developer.android.com/guide/appendix/media-formats.html

**Comment by linsea** [comment]
@KingKatsuma 不好意思，我看错了，MediaPlayer目前不支持RTMP流媒体格式：
http://developer.android.com/guide/appendix/media-formats.html
