### ISSUE TITLE
onErrorListener 只能截获一次，并且截获之后就不能继续播放了，这个怎么处理呢

### ISSUE THREAD

**Issue by genglei** [linsea/UniversalVideoView#7]

**Comment by linsea** [comment]
@genglei 出错之后你应该reset(), 然后重新start()再播，onPrepared之后再seekTo到之前的位置。

**Comment by wcy10586** [comment]
当第二次直接拖到视频结尾时就会报错 错误为MediaPlayer: error (260, -110)

**Comment by androidroadies** [comment]
How to remove This word from videoview 加载中.. using @arr lib..

**Comment by linsea** [comment]
@androidroadies 
fyi: https://github.com/linsea/UniversalVideoView/issues/10

**Comment by kimnamcham** [comment]
same issues, how can resolve this ?
