### ISSUE TITLE
当按下home键的时候

### ISSUE THREAD

**Issue by Brieny** [linsea/UniversalVideoView#8]
视频正在播放的时候
按下home键  并不能保存当前状态
在onSaveInstanceState中调用的 时候
mVideoView.getCurrentPosition()  为 0
在surfaceholder 的 ondestory中调用的 时候
mVideoView.getCurrentPosition()  也为 0

**Comment by linsea** [comment]
@Brieny 在底层，是通过MediaPlayer来读取当前进度的，你可能需要在onPause的生命周期中保存状态到一个字段中，然后在onSaveInstanceState方法中再保存这个字段。

**Comment by yumi0629** [comment]
因为demo在onpause的时候把视频pause掉了 所以getCurrentPosition 但是mSeekPosition有赋值 所以在onresume把进度条seekto到保存的mSeekPosition值就可以了
